services:
  nginx:
    image: nginx:${nginx_version:?error}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /workspace/certbot/conf:/etc/letsencrypt
      - /workspace/certbot/www:/var/www/certbot
      - /concourse/nginx:/etc/nginx/templates
      - /concourse/scripts:/var/script
    environment:
      CONCOURSE_EXTERNAL_DOMAIN: ${CONCOURSE_EXTERNAL_DOMAIN}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    entrypoint: /var/script/startNginx.sh
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  certbot:
    image: certbot/certbot:${certbot_version:?error}
    restart: always
    volumes:
      - /workspace/certbot/conf:/etc/letsencrypt
      - /workspace/certbot/www:/var/www/certbot
      - /concourse/scripts:/var/script
    entrypoint: /var/script/startCertbot.sh
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    
  db:
    image: postgres:${postgres_version:?error}
    restart: always
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: "${CONCOURSE_POSTGRES_PASSWORD}"
      PGDATA: /db
    volumes:
      - /concourse/db:/db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse:${concourse_version:?error}
    restart: always
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./scripts/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: https://${CONCOURSE_EXTERNAL_URL}
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: "${CONCOURSE_POSTGRES_PASSWORD}"
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_GITHUB_CLIENT_ID: "${CONCOURSE_GITHUB_CLIENT_ID}"
      CONCOURSE_GITHUB_CLIENT_SECRET: "${CONCOURSE_GITHUB_CLIENT_SECRET}"
      CONCOURSE_MAIN_TEAM_GITHUB_TEAM: cloudfoundry:wg-app-runtime-platform-networking-extensions-approvers
      CONCOURSE_ADD_LOCAL_USER: admin_concourse:${CONCOURSE_ADMIN_PWD}
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin_concourse
      CONCOURSE_SESSION_SIGNING_KEY: /concourse-keys/session_signing_key
      CONCOURSE_TSA_HOST_KEY: /concourse-keys/tsa_host_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /concourse-keys/authorized_worker_keys
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse:${concourse_version:?error}
    restart: always
    command: worker
    privileged: true
    cap_add:
    - ALL
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    depends_on: [web]
    volumes: ["./scripts/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_TSA_PUBLIC_KEY: /concourse-keys/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /concourse-keys/worker_key
      CONCOURSE_CONTAINERD_DNS_SERVER: "1.1.1.1,8.8.8.8"
      CONCOURSE_GARDEN_DNS_SERVER: "1.1.1.1,8.8.8.8"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
